### ISSUE TITLE
Crash on KitKat

### ISSUE THREAD

**Issue by ale5000-git** [microg/NominatimGeocoderBackend#22]
It crash on KitKat.
I'm using the version 1.2.1 since I haven't found a compiled version of 1.2.2.

Possibly related to #19 but I'm not sure.

```
[ 05-23 02:35:48.973  1892: 2116 I/ActivityManager ]
Start proc org.microg.nlp.backend.nominatim for service org.microg.nlp.backend.nominatim/.BackendService: pid=3735 uid=10049 gids={50049, 3003}

[ 05-23 02:35:49.090  3735: 3735 D/ActivityThread ]
handleBindApplication:org.microg.nlp.backend.nominatim

[ 05-23 02:35:49.098  3735: 3735 D/ActivityThread ]
setTargetHeapUtilization:0.75

[ 05-23 02:35:49.098  3735: 3735 D/ActivityThread ]
setTargetHeapMinFree:524288

[ 05-23 02:35:49.098  3735: 3735 V/ActivityThread ]
org.microg.nlp.backend.nominatim white listed for hwui

[ 05-23 02:35:49.863  3735: 3735 W/dalvikvm ]
VFY: unable to resolve exception class 2436 (Ljava/beans/IntrospectionException;)

[ 05-23 02:35:49.863  3735: 3735 W/dalvikvm ]
VFY: unable to find exception handler at addr 0x11

[ 05-23 02:35:49.863  3735: 3735 W/dalvikvm ]
VFY:  rejected Lorg/yaml/snakeyaml/representer/Representer$RepresentJavaBean;.representData (Ljava/lang/Object;)Lorg/yaml/snakeyaml/nodes/Node;

[ 05-23 02:35:49.863  3735: 3735 W/dalvikvm ]
VFY:  rejecting opcode 0x0d at 0x0011

[ 05-23 02:35:49.863  3735: 3735 W/dalvikvm ]
VFY:  rejected Lorg/yaml/snakeyaml/representer/Representer$RepresentJavaBean;.representData (Ljava/lang/Object;)Lorg/yaml/snakeyaml/nodes/Node;

[ 05-23 02:35:49.863  3735: 3735 W/dalvikvm ]
Verifier rejected class Lorg/yaml/snakeyaml/representer/Representer$RepresentJavaBean;

[ 05-23 02:35:49.863  3735: 3735 D/AndroidRuntime ]
Shutting down VM

[ 05-23 02:35:49.863  3735: 3735 W/dalvikvm ]
threadid=1: thread exiting with uncaught exception (group=0x415d7c20)

[ 05-23 02:35:49.863  3735: 3735 E/AndroidRuntime ]
FATAL EXCEPTION: main
Process: org.microg.nlp.backend.nominatim, PID: 3735
java.lang.VerifyError: org/yaml/snakeyaml/representer/Representer$RepresentJavaBean
	at org.yaml.snakeyaml.representer.Representer.<init>(Representer.java:44)
	at org.yaml.snakeyaml.Yaml.<init>(Yaml.java:63)
	at org.microg.address.Formatter.loadFile(Formatter.java:361)
	at org.microg.address.Formatter.readConfiguration(Formatter.java:332)
	at org.microg.address.Formatter.<init>(Formatter.java:61)
	at org.microg.address.Formatter.<init>(Formatter.java:56)
	at org.microg.nlp.backend.nominatim.BackendService.onCreate(BackendService.java:87)
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:2596)
	at android.app.ActivityThread.access$1800(ActivityThread.java:144)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1287)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:136)
	at android.app.ActivityThread.main(ActivityThread.java:5179)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:732)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:566)
	at dalvik.system.NativeStart.main(Native Method)
```

**Comment by ale5000-git** [comment]
This is fixed in 1.2.2.
